# Generated by Django 3.0.6 on 2020-12-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique value for product page URL, created from name.",
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "meta_keywords",
                    models.CharField(
                        help_text="Comma-delimited set of SEO keywords for meta tag",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        help_text="Content for description meta tag",
                        max_length=255,
                        verbose_name="Meta Description",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique value for product page URL, created from name.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("sku", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=9
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("quantity", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "meta_keywords",
                    models.CharField(
                        help_text="Comma-delimited set of SEO keywords for meta tag",
                        max_length=255,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        help_text="Content for description meta tag", max_length=255
                    ),
                ),
                ("categories", models.ManyToManyField(to="catalog.Category")),
            ],
            options={
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.Product",
                    ),
                ),
            ],
            options={
                "db_table": "product_images",
                "ordering": ["-created_at"],
            },
        ),
    ]
