# Generated by Django 3.0.4 on 2020-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="img_category",
            field=models.CharField(
                choices=[("thumbnail", "thumbnail"), ("other", "other")],
                default="other",
                max_length=20,
            ),
        ),
    ]
