# Generated by Django 3.0.4 on 2021-01-04 10:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productimage_img_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=0,
                size=[120, 120],
                upload_to="",
            ),
        ),
    ]
