# Generated by Django 3.0.4 on 2021-01-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_userprofile_role"),
        ("catalog", "0004_auto_20210104_1022"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.UserProfile",
            ),
            preserve_default=False,
        ),
    ]
