# Generated by Django 3.0.4 on 2021-02-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_auto_20210114_1104"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_five",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_four",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_one",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image_three",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_two",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
