# Generated by Django 3.0.4 on 2021-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_auto_20210201_1529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
