# Generated by Django 3.0.4 on 2021-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_auto_20210201_1542"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
    ]
