# Generated by Django 3.0.4 on 2021-02-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_remove_product_old_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="meta_keywords",
        ),
    ]
