# Generated by Django 3.1.7 on 2021-02-24 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_id',
            field=models.CharField(default=uuid.UUID('1accba6c-2185-40e2-8e25-46ff8ee03ef5'), max_length=150),
        ),
    ]
