# Generated by Django 3.1.7 on 2021-02-24 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210224_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_id',
            field=models.CharField(default=uuid.UUID('2df5a8b5-58ba-4a1d-8922-6a4e8baf05ec'), max_length=150),
        ),
    ]
